export type PublicAcademic = {
  slug: string
  name: string
  institution: string
  department: string
  role: 'PhD Student' | 'Postdoctoral Fellow'
  field: 'Speech & Language' | 'Art & Visual Culture' | 'Bioengineering & Biomedical Engineering'
  location: string
  email: string
  researchAreas: string[]
  summaryZh: string
  summaryEn: string
  sourceUrl: string
  sourceLabel: string
  checkedAt: string
}

/**
 * Public professional information copied from the linked university pages.
 * These records are not platform accounts and must never be treated as
 * verified mentors, bookable providers, or evidence of endorsement.
 */
export const PUBLIC_ACADEMICS: PublicAcademic[] = [
  {
    slug: 'joan-orpella-nyu',
    name: 'Joan Orpella',
    institution: 'New York University',
    department: 'Poeppel Lab',
    role: 'Postdoctoral Fellow',
    field: 'Speech & Language',
    location: 'New York, USA',
    email: 'jo1358@nyu.edu',
    researchAreas: ['Speech production', 'Auditory-motor synchronization', 'Statistical learning', 'BCI'],
    summaryZh: '研究语音产生、听觉—运动同步、语言统计学习、脑机接口与听觉感知。',
    summaryEn: 'Studies speech production, auditory-motor synchronization, statistical learning, BCI, and auditory perception.',
    sourceUrl: 'https://wp.nyu.edu/poeppellab/the-lab/current/',
    sourceLabel: 'NYU Poeppel Lab — Current Members',
    checkedAt: '2026-07-30',
  },
  {
    slug: 'arianna-zuanazzi-nyu',
    name: 'Arianna Zuanazzi',
    institution: 'New York University',
    department: 'Poeppel Lab',
    role: 'Postdoctoral Fellow',
    field: 'Speech & Language',
    location: 'New York, USA',
    email: 'az1864@nyu.edu',
    researchAreas: ['Semantics', 'Syntax', 'Morphology', 'Music cognition', 'Multisensory processing'],
    summaryZh: '研究语言的语义、句法与形态，以及音乐认知、注意、预期和多感官加工。',
    summaryEn: 'Studies semantics, syntax, morphology, music cognition, attention, expectation, and multisensory processing.',
    sourceUrl: 'https://wp.nyu.edu/poeppellab/the-lab/current/',
    sourceLabel: 'NYU Poeppel Lab — Current Members',
    checkedAt: '2026-07-30',
  },
  {
    slug: 'andrew-chang-nyu',
    name: 'Andrew Chang',
    institution: 'New York University',
    department: 'Poeppel Lab',
    role: 'Postdoctoral Fellow',
    field: 'Speech & Language',
    location: 'New York, USA',
    email: 'ac8888@nyu.edu',
    researchAreas: ['Speech perception', 'Music perception', 'Neural oscillations', 'Auditory rhythm'],
    summaryZh: '研究言语与音乐感知、神经振荡、人际互动和听觉节律。',
    summaryEn: 'Studies speech and music perception, neural oscillations, interpersonal interaction, and auditory rhythm.',
    sourceUrl: 'https://wp.nyu.edu/poeppellab/the-lab/current/',
    sourceLabel: 'NYU Poeppel Lab — Current Members',
    checkedAt: '2026-07-30',
  },
  {
    slug: 'omri-raccah-nyu',
    name: 'Omri Raccah',
    institution: 'New York University',
    department: 'Poeppel Lab',
    role: 'PhD Student',
    field: 'Speech & Language',
    location: 'New York, USA',
    email: 'or409@nyu.edu',
    researchAreas: ['Auditory sequences', 'Memory and learning', 'Large-scale brain networks', 'Intracranial EEG'],
    summaryZh: '研究听觉序列表征、记忆与学习、大规模脑网络和颅内脑电。',
    summaryEn: 'Studies auditory sequence representation, memory and learning, large-scale brain networks, and intracranial EEG.',
    sourceUrl: 'https://wp.nyu.edu/poeppellab/the-lab/current/',
    sourceLabel: 'NYU Poeppel Lab — Current Members',
    checkedAt: '2026-07-30',
  },
  {
    slug: 'francesco-mantegna-nyu',
    name: 'Francesco Mantegna',
    institution: 'New York University',
    department: 'Poeppel Lab',
    role: 'PhD Student',
    field: 'Speech & Language',
    location: 'New York, USA',
    email: 'fm1672@nyu.edu',
    researchAreas: ['Speech motor control', 'Speech imagery', 'Sensorimotor transformation'],
    summaryZh: '研究言语运动控制、言语意象和感觉运动转换。',
    summaryEn: 'Studies speech motor control, speech imagery, and sensorimotor transformation.',
    sourceUrl: 'https://wp.nyu.edu/poeppellab/the-lab/current/',
    sourceLabel: 'NYU Poeppel Lab — Current Members',
    checkedAt: '2026-07-30',
  },
  {
    slug: 'phoebe-chen-nyu',
    name: 'Phoebe Chen',
    institution: 'New York University',
    department: 'Poeppel Lab',
    role: 'PhD Student',
    field: 'Speech & Language',
    location: 'New York, USA',
    email: 'hc2896@nyu.edu',
    researchAreas: ['Semantic composition', 'Computational linguistics', 'Interbrain synchrony'],
    summaryZh: '研究语义组合、计算语言学和脑间同步。',
    summaryEn: 'Studies semantic composition, computational linguistics, and interbrain synchrony.',
    sourceUrl: 'https://wp.nyu.edu/poeppellab/the-lab/current/',
    sourceLabel: 'NYU Poeppel Lab — Current Members',
    checkedAt: '2026-07-30',
  },
  {
    slug: 'ellie-abrams-nyu',
    name: 'Ellie Abrams',
    institution: 'New York University',
    department: 'Poeppel Lab',
    role: 'PhD Student',
    field: 'Speech & Language',
    location: 'New York, USA',
    email: 'ellie.abrams@nyu.edu',
    researchAreas: ['Speech-music interface', 'Word learning', 'Language development', 'Music and memory'],
    summaryZh: '研究言语—音乐接口、词汇学习、语言发展以及音乐与记忆。',
    summaryEn: 'Studies the speech-music interface, word learning, language development, and music and memory.',
    sourceUrl: 'https://wp.nyu.edu/poeppellab/the-lab/current/',
    sourceLabel: 'NYU Poeppel Lab — Current Members',
    checkedAt: '2026-07-30',
  },
  {
    slug: 'huanhuan-shi-nyu',
    name: 'Huanhuan Shi',
    institution: 'New York University',
    department: 'Communicative Sciences and Disorders',
    role: 'PhD Student',
    field: 'Speech & Language',
    location: 'New York, USA',
    email: 'hs3035@nyu.edu',
    researchAreas: ['Child language development', 'Language learning', 'Developmental language disorders'],
    summaryZh: '研究儿童语言学习与发展，以及支持典型和非典型语言发展的因素。',
    summaryEn: 'Studies child language learning and development in children with and without language disorders.',
    sourceUrl: 'https://wp.nyu.edu/huanhuanshi/',
    sourceLabel: 'NYU personal academic webpage',
    checkedAt: '2026-07-30',
  },
  {
    slug: 'sarah-hwang-ucsc',
    name: 'Sarah Hwang',
    institution: 'University of California, Santa Cruz',
    department: 'History of Art & Visual Culture',
    role: 'PhD Student',
    field: 'Art & Visual Culture',
    location: 'Santa Cruz, California, USA',
    email: 'shwang30@ucsc.edu',
    researchAreas: ['Contemporary art', 'Digital visual culture', 'Cyberfeminism', 'Asian diaspora'],
    summaryZh: '研究当代艺术、数字视觉与物质文化、网络女性主义、亚洲离散社群、实验出版和街头艺术。',
    summaryEn: 'Studies contemporary art, digital visual and material culture, cyberfeminism, Asian diaspora, experimental publishing, and street art.',
    sourceUrl: 'https://havc.ucsc.edu/people/graduate-students/',
    sourceLabel: 'UC Santa Cruz — History of Art & Visual Culture Graduate Students',
    checkedAt: '2026-07-30',
  },
  {
    slug: 'methaporn-singhanan-ucsc',
    name: 'Methaporn Singhanan',
    institution: 'University of California, Santa Cruz',
    department: 'History of Art & Visual Culture',
    role: 'PhD Student',
    field: 'Art & Visual Culture',
    location: 'Santa Cruz, California, USA',
    email: 'msingha5@ucsc.edu',
    researchAreas: ['Textile curation', 'Buddhist art', 'Southeast Asian art', 'Cultural heritage'],
    summaryZh: '研究纺织品策展、佛教艺术与手稿织物、东南亚艺术史、文化遗产保护和跨区域贸易。',
    summaryEn: 'Studies textile curation, Buddhist art and manuscript textiles, Southeast Asian art history, cultural heritage, and transregional commerce.',
    sourceUrl: 'https://havc.ucsc.edu/people/graduate-students/',
    sourceLabel: 'UC Santa Cruz — History of Art & Visual Culture Graduate Students',
    checkedAt: '2026-07-30',
  },
  {
    slug: 'haerin-jung-rice',
    name: 'Haerin Jung',
    institution: 'Rice University',
    department: 'Department of Art History',
    role: 'PhD Student',
    field: 'Art & Visual Culture',
    location: 'Houston, Texas, USA',
    email: 'haerin.jung@rice.edu',
    researchAreas: ['American abstract art', 'Asian American art', 'Asian diaspora', 'Korean modern art'],
    summaryZh: '研究美国抽象艺术、种族身份、亚洲离散及亚裔美国艺术，以及韩国现代艺术与建筑。',
    summaryEn: 'Studies American abstract art, racial identity, Asian American and diasporic art, and Korean modern art and architecture.',
    sourceUrl: 'https://profiles.rice.edu/student/haerin-jung',
    sourceLabel: 'Rice University — Student Profile',
    checkedAt: '2026-07-30',
  },
  {
    slug: 'matthew-lopez-columbia',
    name: 'Matthew Lopez',
    institution: 'Columbia University',
    department: 'Art History and Archaeology',
    role: 'PhD Student',
    field: 'Art & Visual Culture',
    location: 'New York, USA',
    email: 'msl2232@columbia.edu',
    researchAreas: ['Architectural history', 'Industrial architecture', 'Environmental history', 'History of technology'],
    summaryZh: '研究十九世纪欧美工业建筑相互交织的社会史、环境史和技术史。',
    summaryEn: 'Studies the entangled social, environmental, and technical histories of nineteenth-century industrial architecture in Europe and North America.',
    sourceUrl: 'https://arthistory.columbia.edu/content/matthew-lopez',
    sourceLabel: 'Columbia University — Art History and Archaeology',
    checkedAt: '2026-07-30',
  },
  {
    slug: 'anna-liisa-sepp-columbia',
    name: 'Anna-Liisa Sepp',
    institution: 'Columbia University',
    department: 'Biomedical Engineering · Kam Lab',
    role: 'PhD Student',
    field: 'Bioengineering & Biomedical Engineering',
    location: 'New York, USA',
    email: 'ais2159@columbia.edu',
    researchAreas: ['Biomaterials', 'Immunoengineering', 'CAR T therapy', 'Electrospinning'],
    summaryZh: '研究用于 CAR-T 细胞培养的静电纺丝基底，涉及生物材料、免疫工程和细胞治疗。',
    summaryEn: 'Develops electrospun substrates for growing T cells for CAR T therapy, spanning biomaterials, immunoengineering, and cell therapy.',
    sourceUrl: 'https://kamlab.bme.columbia.edu/people/anna-liisa-sepp',
    sourceLabel: 'Columbia University — Microscale Biocomplexity Lab',
    checkedAt: '2026-07-30',
  },
  {
    slug: 'lauren-chiriboga-columbia',
    name: 'Lauren Chiriboga',
    institution: 'Columbia University',
    department: 'Biomedical Engineering · Fowler Memorial Lab',
    role: 'PhD Student',
    field: 'Bioengineering & Biomedical Engineering',
    location: 'New York, USA',
    email: 'lac2268@columbia.edu',
    researchAreas: ['Auditory biomechanics', 'Hearing science', 'Biomedical engineering'],
    summaryZh: '哥伦比亚大学生物医学工程博士候选人，所在实验室研究听觉系统的生物力学与听力科学。',
    summaryEn: 'A Columbia Biomedical Engineering PhD candidate in a lab focused on auditory biomechanics and hearing science.',
    sourceUrl: 'https://fowlerlab.bme.columbia.edu/content/about',
    sourceLabel: 'Columbia University — Fowler Memorial Lab Members',
    checkedAt: '2026-07-30',
  },
  {
    slug: 'kaitlyn-wong-columbia',
    name: 'Kaitlyn Wong',
    institution: 'Columbia University',
    department: 'Biomedical Engineering · Fowler Memorial Lab',
    role: 'PhD Student',
    field: 'Bioengineering & Biomedical Engineering',
    location: 'New York, USA',
    email: 'kw3140@cumc.columbia.edu',
    researchAreas: ['Auditory biomechanics', 'Hearing science', 'Biomedical engineering'],
    summaryZh: '哥伦比亚大学生物医学工程博士生，所在实验室研究听觉系统的生物力学与听力科学。',
    summaryEn: 'A Columbia Biomedical Engineering PhD student in a lab focused on auditory biomechanics and hearing science.',
    sourceUrl: 'https://fowlerlab.bme.columbia.edu/content/about',
    sourceLabel: 'Columbia University — Fowler Memorial Lab Members',
    checkedAt: '2026-07-30',
  },
  {
    slug: 'joshua-price-harvard',
    name: 'Joshua Price',
    institution: 'Harvard University',
    department: 'Bioengineering · Mooney Lab',
    role: 'PhD Student',
    field: 'Bioengineering & Biomedical Engineering',
    location: 'Cambridge, Massachusetts, USA',
    email: 'joshuaprice@g.harvard.edu',
    researchAreas: ['T-cell development', 'Immunoengineering', 'Cell manufacturing', 'Biomaterials'],
    summaryZh: '研究 T 细胞发育、免疫工程和细胞制造，并在生物材料与再生医学实验室开展博士研究。',
    summaryEn: 'Studies T-cell development, immunoengineering, and cell manufacturing in a biomaterials and regenerative medicine lab.',
    sourceUrl: 'https://mooneylab.seas.harvard.edu/members',
    sourceLabel: 'Harvard University — Mooney Lab Members',
    checkedAt: '2026-07-30',
  },
]

export function getPublicAcademic(slug: string): PublicAcademic | undefined {
  return PUBLIC_ACADEMICS.find(person => person.slug === slug)
}
